/*
 * Copyright Ekagra and SemanticBits, LLC
 * 
 * Distributed under the OSI-approved BSD 3-Clause License.
 * See http://ncip.github.com/ihub/LICENSE.txt for details.
 */
package gov.nih.nci.caxchange.common;

import javax.xml.namespace.QName;


/**
 * This class is autogenerated, DO NOT EDIT
 *
 * @created by Introduce Toolkit version 1.3
 */
public interface CaXchangeConsumerServiceConstantsBase {
	public static final String SERVICE_NS = "http://caxchange.nci.nih.gov/CaXchangeConsumerService";
	public static final QName RESOURCE_KEY = new QName(SERVICE_NS, "CaXchangeConsumerServiceKey");
	public static final QName RESOURCE_PROPERTY_SET = new QName(SERVICE_NS, "CaXchangeConsumerServiceResourceProperties");
	public static final QName SERVICEMETADATA = new QName("gme://caGrid.caBIG/1.0/gov.nih.nci.cagrid.metadata", "ServiceMetadata");
	
}
