package gov.nih.nci.integration.domain;

public enum StrategyIdentifier {
	CATISSUE_CREATE_REGISTRATION,
	CATISSUE_UPDATE_REGISTRATION,
	CAEERS_CREATE_REGISTRATION,
	CAEERS_UPDATE_REGISTRATION,
	CAEERS_CREATE_AE,
	CATISSUE_CREATE_SPECIMEN,
	CATISSUE_UPDATE_SPECIMEN,
	CATISSUE_REGISTER_CONSENT;
}
