
package gov.nih.nci.caxchange.transcend;

import gov.nih.nci.caxchange.messaging.ErrorDetails;
import gov.nih.nci.caxchange.messaging.Message;
import gov.nih.nci.caxchange.messaging.Response;
import gov.nih.nci.caxchange.messaging.ResponseMessage;
import gov.nih.nci.caxchange.messaging.Statuses;

import java.io.StringWriter;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.xml.bind.JAXBContext;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.JAXBException;
import javax.xml.bind.Marshaller;
import javax.xml.namespace.QName;

import org.apache.commons.lang.StringUtils;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.mirth.connect.connectors.ws.AcceptMessage;
import com.mirth.connect.connectors.ws.WebServiceMessageReceiver;
/**
 * This class was generated by Apache CXF 2.4.1
 * 2012-04-12T15:17:59.068-04:00
 * Generated source version: 2.4.1
 * 
 */

@javax.jws.WebService(
                      serviceName = "CaXchangeRequestService",
                      portName = "soap",
                      targetNamespace = "http://caXchange.nci.nih.gov/caxchangerequest",
                      endpointInterface = "gov.nih.nci.caxchange.messaging.CaXchangeRequestPortType")
                      
public class CaXchangeRequestService  extends AcceptMessage{

    private static final Logger LOG = LoggerFactory.getLogger(CaXchangeRequestService.class.getName());
    
//    private String customLibDir = "./custom-lib";
    private String customLibDir = "custom-lib/";
    
    
    public CaXchangeRequestService(WebServiceMessageReceiver webServiceMessageReceiver) {
        super(webServiceMessageReceiver);
    }

   
    @WebResult(name = "responseMessage", targetNamespace = "http://caXchange.nci.nih.gov/caxchangerequest", partName = "parameters")
    @WebMethod
    public gov.nih.nci.caxchange.messaging.ResponseMessage processRequest(
            @WebParam(partName = "parameters", name = "message", 
                    targetNamespace = "http://caXchange.nci.nih.gov/caxchangerequest") Message parameters)
    	{    	
        LOG.info("Executing operation processRequest");
        System.out.println("Message : " + parameters.getRequest().getBusinessMessagePayload().getXmlSchemaDefinition().toString());
        
        gov.nih.nci.caxchange.messaging.ResponseMessage respMessage = new ResponseMessage();
        
        try {
        
        	String reqstr = getCaXchangeRequestxml(parameters);
            
       	 if (StringUtils.isEmpty(reqstr)) {
       		 ErrorDetails errorDetails = new ErrorDetails();
       		 errorDetails.setErrorCode("Empty_Value");
       		 errorDetails.setErrorDescription("RequestXML is empty...");
       		 
       		 Response response = new Response();
       		 response.setCaXchangeError(errorDetails);
             response.setResponseStatus(Statuses.FAILURE);
             
             respMessage.setResponse(response);
       		 return respMessage;
              
            }

            String mcResponse = webServiceMessageReceiver.processData(reqstr);
            
            System.out.println("Inside CaXchangeRequestService... mcResponse is :: " +mcResponse);

            LOG.info("MC RESPONSE:" + mcResponse);
            
            if (mcResponse != null
                    && (mcResponse.indexOf("Error") > -1 || mcResponse.indexOf("Exception") > -1
                            || mcResponse.indexOf("ERROR") > -1 || mcResponse.indexOf("error") > -1)) {
                mcResponse = StringUtils.remove(mcResponse, "SUCCESS:");
                ErrorDetails errorDetails = new ErrorDetails();
          		errorDetails.setErrorCode("Error_Processing_Data");
          		errorDetails.setErrorDescription("Error processing Data from Source System: " + mcResponse);
          		 
          		Response response = new Response();
          		response.setCaXchangeError(errorDetails);
                response.setResponseStatus(Statuses.FAILURE);
                
                respMessage.setResponse(response);
          		return respMessage;               
            }
            
            Response response = new Response();
            response.setResponseStatus(Statuses.SUCCESS);
            respMessage.setResponse(response);            
            
            return respMessage;
        } catch (java.lang.Exception ex) {        	
        	ErrorDetails errorDetails = new ErrorDetails();
      		errorDetails.setErrorCode("Error_Processing_Data");
      		errorDetails.setErrorDescription("Error processing Data from Source System: " + ex);
      		
        	Response response = new Response();
        	response.setCaXchangeError(errorDetails);
            response.setResponseStatus(Statuses.FAILURE);
            
            respMessage.setResponse(response);         
            return respMessage;
        }
    }
    
    
    
    private String getCaXchangeRequestxml(final Message parameter) {
        try {
        	String requestXML= "";       
        	QName qname = new QName("http://caXchange.nci.nih.gov/caxchangerequest", "caxchangerequest");
        	JAXBElement<Message> message = new JAXBElement<Message>(qname, Message.class, parameter);            
        	StringWriter sw = new StringWriter();        	
        	getMarshaller().marshal( message,sw);        	
        	requestXML = sw.toString();        	
        	LOG.error("Inside CaXchangeRequestService... RequestXML is : " + requestXML);
            
            return requestXML;
        } catch (Exception ex) {
        	LOG.error("Error marshalling CaXchangeRequest!", ex);                	 
            return null;
        } 

    }
    
    private Marshaller getMarshaller() throws JAXBException {		
		JAXBContext jc = JAXBContext.newInstance(Message.class);		
		return jc.createMarshaller();		
	}
    
    
}
