DECLARE
   TABLE_EXISTS NUMBER :=0;
BEGIN   

SELECT COUNT(*) INTO TABLE_EXISTS
FROM ALL_TABLES 
WHERE TABLE_NAME = 'CAXCHANGE_MESSAGES';

IF TABLE_EXISTS > 0 THEN
   EXECUTE IMMEDIATE 'DROP TABLE CAXCHANGE_MESSAGES';
END IF;
   

EXECUTE IMMEDIATE 'CREATE TABLE  CAXCHANGE_MESSAGES
(
   MESSAGE_ID  VARCHAR2(500) NOT NULL,
   ORIGINAL_MESSAGE  CLOB,
   PRIMARY KEY (MESSAGE_ID)
)';

SELECT COUNT(*) INTO TABLE_EXISTS
FROM ALL_TABLES 
WHERE TABLE_NAME = 'CAXCHANGE_MESSAGE_TYPES';

IF TABLE_EXISTS > 0 THEN
   EXECUTE IMMEDIATE 'DROP TABLE CAXCHANGE_MESSAGE_TYPES';
END IF;   

EXECUTE IMMEDIATE 'CREATE TABLE  CAXCHANGE_MESSAGE_TYPES
(
   MESSAGE_TYPE  VARCHAR(500) NOT NULL,
   PAYLOAD_NAMESPACE  VARCHAR(500),
   PRIMARY KEY (MESSAGE_TYPE)
)';

SELECT COUNT(*) INTO TABLE_EXISTS
FROM ALL_TABLES 
WHERE TABLE_NAME = 'CAXCHANGE_NAMESPACES';

IF TABLE_EXISTS > 0 THEN
   EXECUTE IMMEDIATE 'DROP TABLE CAXCHANGE_NAMESPACES';
END IF;
   

EXECUTE IMMEDIATE 'CREATE TABLE CAXCHANGE_NAMESPACES
(
   PAYLOAD_NAMESPACE  VARCHAR(500),
   SCHEMA_FILE_NAME   VARCHAR(500),
   PRIMARY KEY (PAYLOAD_NAMESPACE)
)';

END;
/