DELETE FROM CAXCHANGE_MESSAGE_TYPES
/

INSERT ALL
INTO CAXCHANGE_MESSAGE_TYPES(MESSAGE_TYPE,PAYLOAD_NAMESPACE) 
VALUES ('STUDY_CREATION','gme://ccts.cabig/1.0/gov.nih.nci.cabig.ccts.domain')
INTO CAXCHANGE_MESSAGE_TYPES(MESSAGE_TYPE,PAYLOAD_NAMESPACE) 
VALUES ('REGISTER_SUBJECT','gme://ccts.cabig/1.0/gov.nih.nci.cabig.ccts.domain')
INTO CAXCHANGE_MESSAGE_TYPES(MESSAGE_TYPE,PAYLOAD_NAMESPACE) 
VALUES ('LAB_BASED_AE','gme://ccts.cabig/1.0/gov.nih.nci.cabig.ccts.domain.loadlabs')
INTO CAXCHANGE_MESSAGE_TYPES(MESSAGE_TYPE,PAYLOAD_NAMESPACE) 
VALUES ('LOAD_LAB_TO_CDMS','gme://ccts.cabig/1.0/gov.nih.nci.cabig.ccts.domain.loadlabs')
INTO CAXCHANGE_MESSAGE_TYPES(MESSAGE_TYPE,PAYLOAD_NAMESPACE) 
VALUES ('PERSON','http://po.coppa.nci.nih.gov')
INTO CAXCHANGE_MESSAGE_TYPES(MESSAGE_TYPE,PAYLOAD_NAMESPACE) 
VALUES ('IDENTIFIED_PERSON','http://po.coppa.nci.nih.gov')
INTO CAXCHANGE_MESSAGE_TYPES(MESSAGE_TYPE,PAYLOAD_NAMESPACE) 
VALUES ('ORGANIZATION','http://po.coppa.nci.nih.gov')
INTO CAXCHANGE_MESSAGE_TYPES(MESSAGE_TYPE,PAYLOAD_NAMESPACE) 
VALUES ('ORGANIZATIONAL_CONTACT','http://po.coppa.nci.nih.gov')
INTO CAXCHANGE_MESSAGE_TYPES(MESSAGE_TYPE,PAYLOAD_NAMESPACE) 
VALUES ('OVERSIGHT_COMMITTEE','http://po.coppa.nci.nih.gov')
INTO CAXCHANGE_MESSAGE_TYPES(MESSAGE_TYPE,PAYLOAD_NAMESPACE) 
VALUES ('RESEARCH_ORGANIZATION','http://po.coppa.nci.nih.gov')
INTO CAXCHANGE_MESSAGE_TYPES(MESSAGE_TYPE,PAYLOAD_NAMESPACE) 
VALUES ('PERSON_BUSINESS_SERVICE','http://po.coppa.nci.nih.gov')
INTO CAXCHANGE_MESSAGE_TYPES(MESSAGE_TYPE,PAYLOAD_NAMESPACE) 
VALUES ('ORGANIZATION_BUSINESS_SERVICE','http://po.coppa.nci.nih.gov')
INTO CAXCHANGE_MESSAGE_TYPES(MESSAGE_TYPE,PAYLOAD_NAMESPACE) 
VALUES ('IDENTIFIED_ORGANIZATION','http://po.coppa.nci.nih.gov')
INTO CAXCHANGE_MESSAGE_TYPES(MESSAGE_TYPE,PAYLOAD_NAMESPACE) 
VALUES ('CLINICAL_RESEARCH_STAFF','http://po.coppa.nci.nih.gov')
INTO CAXCHANGE_MESSAGE_TYPES(MESSAGE_TYPE,PAYLOAD_NAMESPACE) 
VALUES ('HEALTH_CARE_FACILITY','http://po.coppa.nci.nih.gov')
INTO CAXCHANGE_MESSAGE_TYPES(MESSAGE_TYPE,PAYLOAD_NAMESPACE) 
VALUES ('HEALTH_CARE_PROVIDER','http://po.coppa.nci.nih.gov')
INTO CAXCHANGE_MESSAGE_TYPES(MESSAGE_TYPE,PAYLOAD_NAMESPACE) 
VALUES ('SCHEDULE_MODIFICATION','gme://ccts.cabig/1.0/gov.nih.nci.cabig.ccts.ae.domain')
SELECT * FROM DUAL
/

DELETE FROM CAXCHANGE_NAMESPACES
/

INSERT ALL
INTO CAXCHANGE_NAMESPACES(PAYLOAD_NAMESPACE,SCHEMA_FILE_NAME)
VALUES ('gme://ccts.cabig/1.0/gov.nih.nci.cabig.ccts.domain','ccts.cabig-1.0_gov.nih.nci.cabig.ccts.domain.xsd')
INTO CAXCHANGE_NAMESPACES(PAYLOAD_NAMESPACE,SCHEMA_FILE_NAME)
VALUES ('gme://ccts.cabig/1.0/gov.nih.nci.cabig.ccts.domain.loadlabs','ccts.cabig-1.0_gov.nih.nci.cabig.ccts.domain.loadlabs.xsd')
INTO CAXCHANGE_NAMESPACES(PAYLOAD_NAMESPACE,SCHEMA_FILE_NAME)
VALUES ('http://po.coppa.nci.nih.gov','http_po.coppa.nci.nih.gov.xsd')
INTO CAXCHANGE_NAMESPACES(PAYLOAD_NAMESPACE,SCHEMA_FILE_NAME)
VALUES ('gme://ccts.cabig/1.0/gov.nih.nci.cabig.ccts.ae.domain','ccts.cabig-1.0_gov.nih.nci.cabig.ccts.ae.domain.xsd')
SELECT * FROM DUAL       
/

COMMIT
/