package gov.nih.nci.cagrid.caxchange.client;

import java.io.InputStream;
import java.rmi.RemoteException;

import javax.xml.namespace.QName;

import org.apache.axis.EngineConfiguration;
import org.apache.axis.client.AxisClient;
import org.apache.axis.client.Stub;
import org.apache.axis.configuration.FileProvider;
import org.apache.axis.message.addressing.EndpointReferenceType;
import org.apache.axis.types.URI.MalformedURIException;

import org.oasis.wsrf.properties.GetResourcePropertyResponse;

import org.globus.gsi.GlobusCredential;

import gov.nih.nci.cagrid.caxchange.stubs.CaXchangeRequestProcessorPortType;
import gov.nih.nci.cagrid.caxchange.stubs.service.CaXchangeRequestProcessorServiceAddressingLocator;
import gov.nih.nci.cagrid.caxchange.common.CaXchangeRequestProcessorI;
import gov.nih.nci.cagrid.introduce.security.client.ServiceSecurityClient;

/**
 * This class is autogenerated, DO NOT EDIT GENERATED GRID SERVICE ACCESS METHODS.
 *
 * This client is generated automatically by Introduce to provide a clean unwrapped API to the
 * service.
 *
 * On construction the class instance will contact the remote service and retrieve it's security
 * metadata description which it will use to configure the Stub specifically for each method call.
 * 
 * @created by Introduce Toolkit version 1.3
 */
public class CaXchangeRequestProcessorClient extends CaXchangeRequestProcessorClientBase implements CaXchangeRequestProcessorI {	

	public CaXchangeRequestProcessorClient(String url) throws MalformedURIException, RemoteException {
		this(url,null);	
	}

	public CaXchangeRequestProcessorClient(String url, GlobusCredential proxy) throws MalformedURIException, RemoteException {
	   	super(url,proxy);
	}
	
	public CaXchangeRequestProcessorClient(EndpointReferenceType epr) throws MalformedURIException, RemoteException {
	   	this(epr,null);
	}
	
	public CaXchangeRequestProcessorClient(EndpointReferenceType epr, GlobusCredential proxy) throws MalformedURIException, RemoteException {
	   	super(epr,proxy);
	}

	public static void usage(){
		System.out.println(CaXchangeRequestProcessorClient.class.getName() + " -url <service url>");
	}
	
	public static void main(String [] args){
	    System.out.println("Running the Grid Service Client");
		try{
		if(!(args.length < 2)){
			if(args[0].equals("-url")){
			  CaXchangeRequestProcessorClient client = new CaXchangeRequestProcessorClient(args[1]);
			  // place client calls here if you want to use this main as a
			  // test....
			} else {
				usage();
				System.exit(1);
			}
		} else {
			usage();
			System.exit(1);
		}
		} catch (Exception e) {
			e.printStackTrace();
			System.exit(1);
		}
	}

  public gov.nih.nci.cagrid.caxchange.context.stubs.types.CaXchangeResponseServiceReference processRequestAsynchronously(gov.nih.nci.caxchange.Message caXchangeRequestMessage) throws RemoteException, gov.nih.nci.cagrid.caxchange.stubs.types.CaXchangeFault {
    synchronized(portTypeMutex){
      configureStubSecurity((Stub)portType,"processRequestAsynchronously");
    gov.nih.nci.cagrid.caxchange.stubs.ProcessRequestAsynchronouslyRequest params = new gov.nih.nci.cagrid.caxchange.stubs.ProcessRequestAsynchronouslyRequest();
    gov.nih.nci.cagrid.caxchange.stubs.ProcessRequestAsynchronouslyRequestCaXchangeRequestMessage caXchangeRequestMessageContainer = new gov.nih.nci.cagrid.caxchange.stubs.ProcessRequestAsynchronouslyRequestCaXchangeRequestMessage();
    caXchangeRequestMessageContainer.setCaXchangeRequestMessage(caXchangeRequestMessage);
    params.setCaXchangeRequestMessage(caXchangeRequestMessageContainer);
    gov.nih.nci.cagrid.caxchange.stubs.ProcessRequestAsynchronouslyResponse boxedResult = portType.processRequestAsynchronously(params);
    return boxedResult.getCaXchangeResponseServiceReference();
    }
  }

  public gov.nih.nci.caxchange.ResponseMessage processRequestSynchronously(gov.nih.nci.caxchange.Message caXchangeRequestMessage) throws RemoteException, gov.nih.nci.cagrid.caxchange.stubs.types.CaXchangeFault {
    synchronized(portTypeMutex){
      configureStubSecurity((Stub)portType,"processRequestSynchronously");
    gov.nih.nci.cagrid.caxchange.stubs.ProcessRequestSynchronouslyRequest params = new gov.nih.nci.cagrid.caxchange.stubs.ProcessRequestSynchronouslyRequest();
    gov.nih.nci.cagrid.caxchange.stubs.ProcessRequestSynchronouslyRequestCaXchangeRequestMessage caXchangeRequestMessageContainer = new gov.nih.nci.cagrid.caxchange.stubs.ProcessRequestSynchronouslyRequestCaXchangeRequestMessage();
    caXchangeRequestMessageContainer.setCaXchangeRequestMessage(caXchangeRequestMessage);
    params.setCaXchangeRequestMessage(caXchangeRequestMessageContainer);
    gov.nih.nci.cagrid.caxchange.stubs.ProcessRequestSynchronouslyResponse boxedResult = portType.processRequestSynchronously(params);
    return boxedResult.getCaXchangeResponseMessage();
    }
  }

}
