DROP TABLE IF EXISTS CAXCHANGE_MESSAGES;

CREATE TABLE  CAXCHANGE_MESSAGES
(
   MESSAGE_ID  VARCHAR(500) NOT NULL,
   ORIGINAL_MESSAGE  TEXT,
   PRIMARY KEY (MESSAGE_ID)
);

DROP TABLE  IF EXISTS CAXCHANGE_MESSAGE_TYPES;

CREATE TABLE  CAXCHANGE_MESSAGE_TYPES
(
   MESSAGE_TYPE  VARCHAR(500) NOT NULL,
   PAYLOAD_NAMESPACE  VARCHAR(500),
   PRIMARY KEY (MESSAGE_TYPE)
);

DROP TABLE IF EXISTS CAXCHANGE_NAMESPACES;

CREATE TABLE CAXCHANGE_NAMESPACES
(
   PAYLOAD_NAMESPACE  VARCHAR(500),
   SCHEMA_FILE_NAME   VARCHAR(500),
   PRIMARY KEY (PAYLOAD_NAMESPACE)
);